name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test the app (CI)
      run: |
        echo "Running CI tests before building..."
        python test_ci.py
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Android APK with Docker
      run: |
        echo "Setting up Docker for APK build..."
        
        # Try to pull the image with explicit platform
        docker pull --platform linux/amd64 kivy/buildozer:latest || {
          echo "Failed to pull kivy/buildozer:latest, trying alternative approach..."
          # Alternative: Use a different base image or build locally
          docker pull --platform linux/amd64 python:3.9-slim
        }
        
        # Build the APK
        docker run --rm \
          --platform linux/amd64 \
          -v "${{ github.workspace }}:/home/user/hostcwd" \
          -e PACKAGER=github-actions \
          kivy/buildozer:latest buildozer android debug || {
          echo "Docker build failed, trying alternative method..."
          echo "This might take longer but should work..."
          
          # Alternative: Install buildozer directly
          pip install buildozer
          buildozer android debug
        }
        
    - name: Find and upload APK
      uses: actions/upload-artifact@v4
      with:
        name: demonling-apk
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/bin/*.apk
        retention-days: 30
        
    - name: Build summary
      run: |
        echo "Build completed!"
        echo "APK files found:"
        find . -name "*.apk" -type f || echo "No APK files found"