name: Comprehensive Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: |
        pip install -r requirements.txt
        python test_ci.py

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Android Build Dependencies
      run: |
        echo "Installing Android build dependencies..."
        
        # Update package list
        sudo apt-get update
        
        # Install Java and Android SDK
        sudo apt-get install -y openjdk-11-jdk
        sudo apt-get install -y android-sdk
        
        # Install Python dependencies
        pip install buildozer cython
        
        # Install additional system dependencies
        sudo apt-get install -y \
          build-essential \
          git \
          python3 \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          python3-dev \
          libffi-dev \
          libssl-dev \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev
        
        echo "Dependencies installed successfully!"
        
    - name: Build Android APK
      run: |
        echo "Building Android APK..."
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: demonling-apk
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/bin/*.apk
        retention-days: 30
        
    - name: Build Summary
      run: |
        echo "Build completed!"
        echo "APK files found:"
        find . -name "*.apk" -type f || echo "No APK files found" 