name: GitHub Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: |
        pip install -r requirements.txt
        python test_ci.py

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-dev \
          libffi-dev \
          libssl-dev \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake
        
    - name: Install Buildozer
      run: |
        pip install buildozer cython
        
    - name: Verify Android SDK
      run: |
        echo "Verifying Android SDK installation..."
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        
        # Check if Android SDK exists
        if [ -d "/usr/local/lib/android/sdk" ]; then
          echo "✅ Android SDK found at /usr/local/lib/android/sdk"
          ls -la /usr/local/lib/android/sdk/
        else
          echo "❌ Android SDK not found at /usr/local/lib/android/sdk"
          exit 1
        fi
        
        # Check build tools
        if [ -d "/usr/local/lib/android/sdk/build-tools" ]; then
          echo "✅ Build tools found"
          ls -la /usr/local/lib/android/sdk/build-tools/
        else
          echo "❌ Build tools not found"
          exit 1
        fi
        
        # Check NDK
        if [ -d "/usr/local/lib/android/sdk/ndk" ]; then
          echo "✅ NDK found"
          ls -la /usr/local/lib/android/sdk/ndk/
        else
          echo "❌ NDK not found"
          exit 1
        fi
        
    - name: Build APK
      run: |
        # Set environment variables
        export ANDROID_HOME=/usr/local/lib/android/sdk
        export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.0
        
        echo "Building Android APK..."
        echo "Using Android SDK at: $ANDROID_HOME"
        echo "Buildozer configuration:"
        cat buildozer.spec | grep -E "(android\.sdk_path|android\.ndk_path|android\.api|android\.minapi)"
        
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: demonling-apk
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/bin/*.apk
        retention-days: 30
        
    - name: Build Summary
      run: |
        echo "Build completed!"
        echo "APK files found:"
        find . -name "*.apk" -type f || echo "No APK files found" 