name: Robust Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: |
        pip install -r requirements.txt
        python test_ci.py

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3 \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          python3-dev \
          libffi-dev \
          libssl-dev \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          openjdk-11-jdk
        
    - name: Install Buildozer
      run: |
        pip install buildozer cython
        
    - name: Configure Buildozer
      run: |
        # Create a minimal buildozer.spec if it doesn't exist
        if [ ! -f "buildozer.spec" ]; then
          buildozer init
        fi
        
        # Update buildozer.spec with proper settings
        sed -i 's/# android.api = 31/android.api = 33/' buildozer.spec
        sed -i 's/# android.minapi = 21/android.minapi = 21/' buildozer.spec
        sed -i 's/# android.ndk = 25b/android.ndk = 25b/' buildozer.spec
        sed -i 's/# android.sdk = 33/android.sdk = 33/' buildozer.spec
        
    - name: Build APK
      run: |
        echo "Building Android APK..."
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: demonling-apk
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/bin/*.apk
        retention-days: 30
        
    - name: Build Summary
      run: |
        echo "Build completed!"
        echo "APK files found:"
        find . -name "*.apk" -type f || echo "No APK files found" 