name: Robust Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: |
        pip install -r requirements.txt
        python test_ci.py

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3 \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          python3-dev \
          libffi-dev \
          libssl-dev \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          openjdk-11-jdk \
          wget \
          unzip
        
    - name: Install Android SDK and Build Tools
      run: |
        echo "Installing Android SDK and build tools..."
        
        # Create Android SDK directory in the expected buildozer location
        mkdir -p ~/.buildozer/android/platform/android-sdk
        
        # Download and install Android SDK command line tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q commandlinetools-linux-11076708_latest.zip -d ~/.buildozer/android/platform/android-sdk/
        mv ~/.buildozer/android/platform/android-sdk/cmdline-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools-latest
        mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
        mv ~/.buildozer/android/platform/android-sdk/cmdline-tools-latest ~/.buildozer/android/platform/android-sdk/cmdline-tools/
        
        # Set environment variables
        export ANDROID_HOME=~/.buildozer/android/platform/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        
        # Accept licenses
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        
        # Install required SDK components
        ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.0" \
          "ndk;25.2.9519653"
        
        # Verify build tools installation
        echo "Verifying build tools installation..."
        ls -la ~/.buildozer/android/platform/android-sdk/build-tools/
        ls -la ~/.buildozer/android/platform/android-sdk/build-tools/33.0.0/
        
        echo "Android SDK and build tools installed successfully!"
        
    - name: Install Buildozer
      run: |
        pip install buildozer cython
        
    - name: Configure Buildozer
      run: |
        # Set environment variables for buildozer
        export ANDROID_HOME=~/.buildozer/android/platform/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.0
        
        # Create a minimal buildozer.spec if it doesn't exist
        if [ ! -f "buildozer.spec" ]; then
          buildozer init
        fi
        
        # Update buildozer.spec with proper settings
        sed -i 's/# android.api = 31/android.api = 33/' buildozer.spec
        sed -i 's/# android.minapi = 21/android.minapi = 21/' buildozer.spec
        sed -i 's/# android.ndk = 25b/android.ndk = 25b/' buildozer.spec
        sed -i 's/# android.sdk = 33/android.sdk = 33/' buildozer.spec
        
        # Set the Android SDK path explicitly in buildozer.spec
        echo "android.sdk_path = ~/.buildozer/android/platform/android-sdk" >> buildozer.spec
        
    - name: Build APK
      run: |
        # Set environment variables for buildozer
        export ANDROID_HOME=~/.buildozer/android/platform/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.0
        
        echo "Building Android APK..."
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "PATH: $PATH"
        echo "Build tools location:"
        ls -la ~/.buildozer/android/platform/android-sdk/build-tools/33.0.0/
        
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: demonling-apk
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/bin/*.apk
        retention-days: 30
        
    - name: Build Summary
      run: |
        echo "Build completed!"
        echo "APK files found:"
        find . -name "*.apk" -type f || echo "No APK files found" 