name: Simple Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run CI tests
      run: |
        echo "Running CI tests..."
        python test_ci.py
        
    - name: Check buildozer.spec
      run: |
        echo "Checking buildozer.spec..."
        if [ -f "buildozer.spec" ]; then
          echo "✅ buildozer.spec exists"
          grep "title = Demonling" buildozer.spec && echo "✅ Title configured"
          grep "package.name = demonling" buildozer.spec && echo "✅ Package name configured"
        else
          echo "❌ buildozer.spec not found"
          exit 1
        fi

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build APK with Docker
      run: |
        echo "Setting up Docker for APK build..."
        
        # Try to pull the image with explicit platform
        docker pull --platform linux/amd64 kivy/buildozer:latest || {
          echo "Failed to pull kivy/buildozer:latest, trying alternative approach..."
          # Alternative: Use a different base image or build locally
          docker pull --platform linux/amd64 python:3.9-slim
        }
        
        # Build the APK
        docker run --rm \
          --platform linux/amd64 \
          -v "${{ github.workspace }}:/home/user/hostcwd" \
          -e PACKAGER=github-actions \
          kivy/buildozer:latest buildozer android debug || {
          echo "Docker build failed, trying alternative method..."
          echo "This might take longer but should work..."
          
          # Alternative: Install buildozer and dependencies directly
          pip install buildozer cython
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          buildozer android debug
        }
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: demonling-apk
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/bin/*.apk
        retention-days: 30
        
    - name: List APK files
      run: |
        echo "APK files found:"
        find . -name "*.apk" -type f || echo "No APK files found" 