name: Working Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: |
        pip install -r requirements.txt
        python test_ci.py

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-dev \
          libffi-dev \
          libssl-dev \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake
        
    - name: Install Buildozer
      run: |
        pip install buildozer cython
        
    - name: Create Minimal buildozer.spec
      run: |
        # Create a minimal buildozer.spec that lets buildozer handle everything
        echo "[app]" > buildozer.spec
        echo "title = Demonling" >> buildozer.spec
        echo "package.name = demonling" >> buildozer.spec
        echo "package.domain = org.demonling" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "source.include_exts = py,png,jpg,kv,atlas,json" >> buildozer.spec
        echo "version = 1.0.0" >> buildozer.spec
        echo "requirements = python3,kivy,pillow" >> buildozer.spec
        echo "orientation = portrait" >> buildozer.spec
        echo "fullscreen = 0" >> buildozer.spec
        echo "android.presplash_color = #000000" >> buildozer.spec
        echo "android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE,WAKE_LOCK" >> buildozer.spec
        echo "android.api = 33" >> buildozer.spec
        echo "android.minapi = 21" >> buildozer.spec
        echo "android.sdk = 33" >> buildozer.spec
        echo "android.ndk = 25b" >> buildozer.spec
        echo "android.private_storage = True" >> buildozer.spec
        echo "android.accept_sdk_license = True" >> buildozer.spec
        echo "android.entrypoint = org.kivy.android.PythonActivity" >> buildozer.spec
        echo "android.archs = arm64-v8a, armeabi-v7a" >> buildozer.spec
        
        echo "Created minimal buildozer.spec:"
        cat buildozer.spec
        
    - name: Build APK
      run: |
        echo "Building Android APK..."
        echo "Using buildozer.spec:"
        cat buildozer.spec
        
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: demonling-apk
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/bin/*.apk
        retention-days: 30
        
    - name: Build Summary
      run: |
        echo "Build completed!"
        echo "APK files found:"
        find . -name "*.apk" -type f || echo "No APK files found" 